### ISSUE TITLE
unicode again?

### ISSUE THREAD

**Issue by h31p** [b-jesch/service.sleepy.watchdog#5]
such messages are shown in kodi.log periodically:

`
2020-04-24 20:28:24.828 T:4991   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xd0 in position 33: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.sleepy.watchdog/default.py", line 42, in onNotification
                                                notifyLog('data:   %s' % (data))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.sleepy.watchdog/default.py", line 22, in notifyLog
                                                xbmc.log('[%s] %s' % (__addonname__, message.encode('utf-8')), level)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 33: ordinal not in range(128)
                                            -->End of Python script error report<--
`

i'm using ukrainian locale in kodi, so cyrillic text is used widely.

not sure if it's related, but sometimes (not always) addon refusing to make defined actions - just doing nothing when idle time is over.

**Comment by b-jesch** [comment]
Which version of the addon? There is no significant code on line 22 nor on line 42 in default.py (default.py ends at line #35).

**Comment by h31p** [comment]
0.1.20, installed through official kodi repo

**Comment by b-jesch** [comment]
You may install the "Kodinerds Repository" as this goes online next week. All addons of this repo are up to date.

https://repo.kodinerds.net/repo --> choose "Download Repo Addon" from navigation bar. after install this should initiate an update of watchdog to 0.1.29.

Greetings
